apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-arq
spec:
  selector:
    matchLabels:
      run: python-arq
  replicas: 2
  template:
    metadata:
      labels:
        run: python-arq
    spec:
      containers:
      # el nombre de la imagen (en este caso dentro de docker hub)
      - image: th39uan60/python_arq
        # aquí se definen las recursos que usará cada POD a desplegar de esta aplicación
        resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 60m
              memory: 500Mi
        ports:
        # puerto de salida del contenedor
        - containerPort: 80
        name: pythonarq-container
        # aquí se definen los "secrets" que se usarán como variables de entorno
        env: 
        - name: USUARIOBD
          valueFrom:
            secretKeyRef:
              name: pythonsecrets
              key: usuario_bd
        - name: PASSWORDBD
          valueFrom:
            secretKeyRef:
              name: pythonsecrets
              key: password_bd