apiVersion: v1
kind: Secret
metadata:
  name: pythonsecrets
  namespace: python-arq
type: Opaque
stringData:
    # aquí se definen los secrets (codificados en base64)
    usuario_bd: "YWRtaW5fYmQ="
    password_bd: "cDQkJHcwcmQ="